title: KV Internal Documentation
description: Internal documentation and runbooks
baseurl: "/kv-internal-docs"
url: "https://squareup.github.io"

# Theme settings
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "KV Internal Docs on GitHub":
    - "//github.com/squareup/kv-internal-docs"

# Enable copy code button
enable_copy_code_button: true

# Default YAML values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache